; dobby-desktop.iss — Inno Setup script for the Dobby OS Desktop per-user installer.
; Authored in Mission 4 (Packager). Compiled by build-release.ps1 (repo root),
; which also generates build\SOURCE-NOTICE.txt referenced below — do NOT compile
; this file standalone unless that notice file already exists.
;
; Design choices (and why):
;   * PER-USER install: PrivilegesRequired=lowest + DefaultDirName under
;     {localappdata}\Programs. No UAC prompt, no admin — matches how the app
;     stores its data (%LOCALAPPDATA%\Dobby) and keeps the friend-install
;     experience one-click.
;   * The payload is the ALREADY-BUILT onedir at ..\dist\DobbyOS (Missions 1-3
;     verified it; hashes recorded). This script must never trigger a rebuild.
;   * SetupIconFile is OMITTED on purpose: the repo ships no .ico asset (the
;     PyInstaller exe itself is built without an icon), so the installer uses
;     the stock Inno icon rather than inventing branding that doesn't exist.
;   * LicenseFile shows the AGPL-3.0 text at install time (the repo LICENSE).
;     Complete corresponding source ships NEXT TO this installer as
;     SOURCE-DobbyOS-1.1.0.zip (AGPL section 6(a) — source accompanies the
;     distribution); SOURCE-NOTICE.txt lands in {app} to say exactly that.
;   * lzma2 compression (solid): best ratio for a 233 MB Python onedir tree.

#define MyAppName "Dobby OS Desktop"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "xicoocosta"
#define MyAppExeName "DobbyOS.exe"

[Setup]
; AppId is the uninstall-registry identity — keep it STABLE across versions so
; upgrades replace instead of duplicating. Generated once in Mission 4.
AppId={{9E64D977-6C9B-4779-80AD-BCD07F85516E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
VersionInfoVersion={#MyAppVersion}.0
DefaultDirName={localappdata}\Programs\DobbyOS
; Per-user, no admin, ever. {localappdata} needs no elevation.
PrivilegesRequired=lowest
; No "Start Menu folder" wizard page — one shortcut, no folder ceremony.
DisableProgramGroupPage=yes
; AGPL-3.0 text shown (and must be accepted) during install.
LicenseFile=..\LICENSE
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
; The onedir payload is x64-only (built with 64-bit CPython).
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={#MyAppName}
OutputDir=..\dist\release
OutputBaseFilename=DobbyOS-Setup-{#MyAppVersion}
; SetupIconFile intentionally omitted — no icon asset exists in the repo.

[Tasks]
; Desktop shortcut is OPT-IN (unchecked by default) — polite for a friend's PC.
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The entire verified onedir tree, recursively. ignoreversion: these are not
; versioned system DLLs — always overwrite on upgrade.
Source: "..\dist\DobbyOS\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion
; Friend-facing install/first-run notes.
Source: "INSTALL.txt"; DestDir: "{app}"; Flags: ignoreversion
; AGPL corresponding-source pointer, generated by build-release.ps1 step 3.
Source: "..\build\SOURCE-NOTICE.txt"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Start Menu shortcut always; {autoprograms} resolves per-user here because
; PrivilegesRequired=lowest.
Name: "{autoprograms}\Dobby OS"; Filename: "{app}\{#MyAppExeName}"
; Desktop shortcut only when the desktopicon task was ticked.
Name: "{autodesktop}\Dobby OS"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Optional post-install launch, checked by default on the finish page.
; nowait: the app is a tray-resident server — the wizard must not block on it.
Filename: "{app}\{#MyAppExeName}"; Description: "Launch Dobby OS"; Flags: nowait postinstall skipifsilent

; [UninstallDelete] — DELIBERATELY ABSENT.
; Uninstall removes only what Setup installed under {app}. User data lives in
; %LOCALAPPDATA%\Dobby (accounts, chats, settings, signing keys) and is NEVER
; touched by uninstall — stated in INSTALL.txt too. If a user truly wants a
; scorched-earth removal they delete %LOCALAPPDATA%\Dobby by hand.
